[package]
name = "caracalcraft"
version = "0.1.0"
edition = "2021"

[dependencies]
hecs = "0.10.5"
macaw = "0.19.1"
yaks = { version = "0.1.0", features = ["parallel"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
