#[repr(u8)]
pub enum PacketId {
    KeepAlive,
    Login,
    Handshake,
    Chat,
    UpdateTime,
    PlayerInventory,
    SpawnPosition,
    Flying = 10,
    PlayerPosition,
    PlayerLook,
    PlayerLookMove,
    BlockDig,
    Place,
    BlockItemSwitch,
    AddToInventory,
    ArmAnimation,
    NamedEntitySpawn = 20,
    PickupSpawn,
    Collect,
    VehicleSpawn,
    MobSpawn,
    DestroyEntity = 29,
    Entity,
    RelEntityMove,
    EntityLook,
    RelEntityMoveLook,
    EntityTeleport,
    PreChunk = 50,
    MapChunk,
    MultiBlockChange,
    BlockChange,
    ComplexEntity = 59,
    KickDisconnect = 255,
}
